# Generated by Django 5.2.4 on 2025-08-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade_id',
            new_name='id_especialidade',
        ),
    ]
