# Generated by Django 5.2.4 on 2025-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_rename_especialidade_id_medico_id_especialidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='descricao',
            field=models.TextField(verbose_name='Descrição da especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='id_especialidade',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador único da especialidade'),
        ),
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome da especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de nascimento do médico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Endereço de e-mail do médico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='endereco',
            field=models.CharField(max_length=50, verbose_name='Endereço de consultório ou residência do médico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_medico',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificador único do médico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome completo do médico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(max_length=13, verbose_name='Número de telefone do médico'),
        ),
    ]
