# Generated by Django 5.2.4 on 2025-08-28 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_alter_especialidade_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='id_especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.especialidade'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_medico',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador único do médico'),
        ),
    ]
