# Generated by Django 5.2.4 on 2025-08-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_medico_id_especialidade_alter_medico_id_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='id_especialidade',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Identificador único da especialidade'),
        ),
    ]
